import type { DietStats } from "../types/api";

/**
 * The summary is built from the numbers the API already returned — no separate
 * counting happens here, and no sentence claims anything the data does not say.
 * Deliberately not generated by an AI model: a fixed template is verifiable
 * line by line, and it cannot drift into diagnosing the user's diet.
 */

const MEAL_LABELS: Record<string, string> = {
  breakfast: "아침",
  lunch: "점심",
  dinner: "저녁",
  snack: "간식",
};

/** Describe how the clean ratio moved against the window before this one. */
export function trendSentence(delta: number, previousTotal: number): string {
  if (previousTotal === 0) return "지난주에는 기록이 없어 비교할 수 없습니다.";
  if (delta === 0) return "지난주와 클린식 비율이 같습니다.";
  const direction = delta > 0 ? "높아졌습니다" : "낮아졌습니다";
  return `지난주보다 클린식 비율이 ${Math.abs(delta)}%p ${direction}.`;
}

/** Build the summary as one sentence per line, skipping what the data cannot support. */
export function buildWeeklySummary(stats: DietStats): string[] {
  if (stats.total === 0) return [];

  const lines = [
    `총 ${stats.total}회의 식사를 기록했습니다.`,
    `클린식은 ${stats.clean}회, 자유식은 ${stats.free}회 기록했습니다.`,
  ];

  const topMealLabel = stats.topMeal ? MEAL_LABELS[stats.topMeal] : null;
  if (topMealLabel) {
    lines.push(`가장 많이 기록한 식사 시간은 ${topMealLabel}입니다.`);
  }

  lines.push(
    `${stats.range.days}일 중 ${stats.recordedDays}일을 기록했습니다.`,
    trendSentence(stats.cleanRatioDelta, stats.previous.total),
  );

  return lines;
}
